### ISSUE TITLE
To which versions of DokuWiki is this script compatible?

### ISSUE THREAD

**Issue by Michaelsy** [splitbrain/dokuwiki-recover#1]
To which versions of DokuWiki is this script compatible?

(🥇 for the realisation!)

**Comment by splitbrain** [comment]
Hmm... most certainly with the most recent (which probably is what people have when they need to recover, because their upgrade broke things). But I think it should work back to any version supporting conf/plugins.conf which seems to have been added about 6 years ago.

**Comment by Michaelsy** [comment]
The required PHP version is hard coded with one fixed value and therefore only valid for Greebo.
